os: osx
language: generic
env:
  - MB_PYTHON_VERSION=3.5
before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install
  - which python3
  - python3 -c 'import sys; print(sys.version)'
install:
  - pip3 install -r requirements.txt
  - pip3 install -U "py2app==0.14"
script:
  # py2app chokes when the extensions are not built explicitely
  - python3 setup.py build_ext --inplace
  - python3 setup.py py2app
  # prepare a dmg out of friture.app
  - export DMG_FILENAME=friture-$(python3 -c 'import friture; print(friture.__version__)')-$(date +'%Y%m%d').dmg
  - echo $DMG_FILENAME
  - hdiutil create $DMG_FILENAME -volname "Friture" -fs HFS+ -srcfolder ../friture-dist/
  - du -hs ../friture-dist/friture.app
  - du -hs $DMG_FILENAME
deploy:
  provider: releases
  draft: true
  api_key:
    secure: N19tf9SJmo3KluUL3DjGMxTTGaa9/qu6UNxqPtOyRu/StSzU1yeh1D8oZr+qYl6tWeqogvSWKlDw78Dp1c4Ro0IQB7ebgxT4YJGF6DeuCo1gvi1uE84Xh+Hl+Y4urS52F3ABSAHejhYhJW7XxsrA3MCiz56S7OEsuDp1u4fG8LM=
  file: $DMG_FILENAME
  skip_cleanup: true
  on:
    repo: tlecomte/friture
